### PR TITLE
add name and version checks

### PR DESCRIPTION
**Pull request by japhir**

### CODE REVIEW

**Comment by japhir** [comment]
see also #5

**Comment by aitap** [comment]
In theory, the user may be requesting an older version of cmocean,
which may be using different palette names, see #1 and Details
in ?cmocean
<https://github.com/aitap/cmocean/blob/a70300f744609b25b995a2ae99026d5bbb247f5b/man/cmocean.Rd#L56>.

It should be simpler to check for `version %in% names(palettes) && name
%in% names(palettes[[version]])`. Personally, I'd go for a `stopifnot`
instead of a warning here. After all, the postcondition of the function
wouldn't be possible to establish for an unknown palette. On the other
hand, we could use `match.arg` to save the user some typing.

-- 
Best regards,
Ivan

**Comment by japhir** [comment]
ah ok, yeah sounds like a good plan to stick to proper version parameter names.

And also, it simplifies by quite a lot! I'm not too sure about match.arg, I'd prefer to type stuff out fully, but this does look elegant.

**Comment by japhir** [comment]
Also, is there any way to have the error message when it fails be more informative still? e.g. changing it into "'version' should be one of ..."

``` r
cmocean("haline", "2.2")(4)
#>Error in match.arg(version, names(palettes)) : 
#>  'arg' should be one of “0.03”, “0.1”, “0.2”, “0.2.1”, “0.2.2”, “0.3”, “1.0”, “1.1”, “1.2”, “2.0”
```

**Comment by aitap** [comment]
Sorry, 'arg' is baked into match.arg source:

https://github.com/wch/r-source/blob/812528de527e9c907118cbea5b99d79eadb2a1a7/src/library/base/R/match.R#L50

I guess that a small helper is in order:

.checkmatch <- function(arg, choices)
 if (!(arg %in% choices)) stop(
  sQuote(deparse(substitute(arg))),
  ' must be one of ',
  paste(dQuote(choices), collapse = ", ")
 )

Perhaps we don't want the partial matching, after all.

-- 
Best regards,
Ivan

**Comment by japhir** [comment]
I also added the `call. = FALSE` parameter to the `stop` call, not sure if that's desired.

**Comment by aitap** [comment]
Thanks!

Is it okay if I include your e-mail address from the Git commits in the
DESCRIPTION? If you are fine with the rest of the changes I've just
pushed, I can merge this pull request.

-- 
Best regards,
Ivan

**Comment by japhir** [comment]
Great! Yeah sure, you can add iljakocken <at> gmail.com (in the hopes that bots won't find me for spamming)

**Review by japhir — COMMENTED** [review]
:+1:

**Pull request merged**
