### PR TITLE
add vignette content

### PR DESCRIPTION
**Pull request by richardsc**

### CODE REVIEW

**Comment by aitap** [comment]
The vignette is looking great, thank you!

For some reason, on my machine the resulting HTML has a `<title>` taken from the first `<h1>` tag of the document, so I'm adding the document title manually.

And now for a slightly awkward question: would you consider yourself to be `aut` of or `ctb` to this package?

**Comment by richardsc** [comment]
Weird, this is what I get (with the version I committed):
image

`ctb` is appropriate I think. Happy to help of course!

**Comment by richardsc** [comment]
With your update, I now see this:
image

**Comment by aitap** [comment]
This is unfortunate: I don't get a title at all unless I add one manually.
single_title
~It might be caused by outdated packages. I'll try upgrading `knitr` and `rmarkdown` and their dependencies.~ Another possible cause is outdated pandoc binary: rstudio/rmarkdown#470

**Pull request merged**
